-- Seed common skills
-- Auto-generated from data/skills/common.json
-- Generated: 2025-11-17T08:55:35.754Z
-- Total skills: 55

INSERT INTO skills (
  name,
  icon,
  is_high_res_icon,
  description,
  skill_type_id,
  profession_id,
  attribute_id,
  attribute_progression,
  energy_cost,
  adrenaline_cost,
  upkeep_cost,
  sacrifice_cost,
  overcast_cost,
  activation_time,
  recharge_time,
  is_elite,
  release_id,
  limitation,
  wiki_url
)
VALUES
  (
    'Resurrection Signet',
    'https://wiki.guildwars.com/images/e/e0/Resurrection_Signet.jpg',
    false,
    'Signet. Resurrects target party member (100% Health, 25% Energy). This signet only recharges when you gain a morale boost.',
    (SELECT id FROM skill_types WHERE name = 'Signet'),
    NULL,
    NULL,
    '{}'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    3,
    'morale boost',
    false,
    (SELECT id FROM releases WHERE name = 'Core'),
    NULL,
    'https://wiki.guildwars.com/wiki/Resurrection_Signet'
  ),
  (
    'Signet of Capture',
    'https://wiki.guildwars.com/images/8/8d/Signet_of_Capture.jpg',
    false,
    'Signet. Choose one skill from a nearby dead Boss of your profession. Signet of Capture is permanently replaced by that skill. If that skill was elite, gain 250 XP for every level you have earned.',
    (SELECT id FROM skill_types WHERE name = 'Signet'),
    NULL,
    NULL,
    '{}'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    2,
    '2',
    false,
    (SELECT id FROM releases WHERE name = 'Core'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Signet_of_Capture'
  ),
  (
    'Lightbringer Signet',
    'https://wiki.guildwars.com/images/4/43/Lightbringer_Signet.jpg',
    false,
    'Signet. You gain {{AdrenalineGain}} strikes of adrenaline and {{EnergyGain}} Energy if you are within the area of a demonic servant of Abaddon.',
    (SELECT id FROM skill_types WHERE name = 'Signet'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Lightbringer rank' LIMIT 1),
    '{"AdrenalineGain":{"3":4,"4":5,"5":5,"6":5,"7":5,"8":5},"EnergyGain":{"3":22,"4":24,"5":24,"6":24,"7":24,"8":24}}'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0.25,
    '25',
    false,
    (SELECT id FROM releases WHERE name = 'Nightfall'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Lightbringer_Signet'
  ),
  (
    'Lightbringer''s Gaze',
    'https://wiki.guildwars.com/images/c/c6/Lightbringer%27s_Gaze.jpg',
    false,
    'Skill. Target demonic servant of Abaddon takes 100 holy damage and is interrupted. Hits one additional foe in the area for each rank of Lightbringer you have attained. This skill is disabled (15 seconds).',
    (SELECT id FROM skill_types WHERE name = 'Skill'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Lightbringer rank' LIMIT 1),
    '{}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '15',
    false,
    (SELECT id FROM releases WHERE name = 'Nightfall'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Lightbringer%27s_Gaze'
  ),
  (
    'Sunspear Rebirth Signet',
    'https://wiki.guildwars.com/images/e/e0/Sunspear_Rebirth_Signet.jpg',
    false,
    'Signet. Resurrect target dead ally at your location (full Health and 10% Energy for each Sunspear Rank attained). This signet only recharges when you gain a morale boost.',
    (SELECT id FROM skill_types WHERE name = 'Signet'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Sunspear rank' LIMIT 1),
    '{"EnergyPercentage":{"0":0,"1":10,"2":20,"3":30,"4":40,"5":50,"6":60,"7":70,"8":80,"9":90,"10":100}}'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    3,
    'morale boost',
    false,
    (SELECT id FROM releases WHERE name = 'Nightfall'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Sunspear_Rebirth_Signet'
  ),
  (
    'Air of Superiority',
    'https://wiki.guildwars.com/images/9/9f/Air_of_Superiority.jpg',
    false,
    'Skill. ({{Duration}} seconds). Gain a random Asura benefit every time you earn experience from killing an enemy.',
    (SELECT id FROM skill_types WHERE name = 'Skill'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"Duration":{"0":20,"1":22,"2":24,"3":26,"4":28,"5":30,"6":30,"7":30,"8":30,"9":30,"10":30}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '20',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Air_of_Superiority'
  ),
  (
    'Asuran Scan',
    'https://wiki.guildwars.com/images/a/a0/Asuran_Scan.jpg',
    false,
    'Hex Spell. ({{Duration}} seconds.) You cannot miss target foe. If you kill this foe, you lose 5% Death Penalty.',
    (SELECT id FROM skill_types WHERE name = 'Hex Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"Duration":{"0":9,"1":10,"2":10,"3":11,"4":11,"5":12,"6":12,"7":12,"8":12,"9":12,"10":12}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '5',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Asuran_Scan'
  ),
  (
    'Mental Block',
    'https://wiki.guildwars.com/images/e/ed/Mental_Block.jpg',
    false,
    'Enchantment Spell. ({{Duration}} seconds.) You have a 50% chance to block. Renewal: every time an enemy hits you.',
    (SELECT id FROM skill_types WHERE name = 'Enchantment Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"Duration":{"0":5,"1":6,"2":7,"3":9,"4":10,"5":11,"6":11,"7":11,"8":11,"9":11,"10":11}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '15',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Mental_Block'
  ),
  (
    'Mindbender',
    'https://wiki.guildwars.com/images/c/c0/Mindbender.jpg',
    false,
    'Enchantment Spell. ({{Duration}} seconds.) You move {{SpeedBoostPercent}}% faster and cast Spells 20% faster.',
    (SELECT id FROM skill_types WHERE name = 'Enchantment Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"Duration":{"0":10,"1":11,"2":12,"3":14,"4":15,"5":16,"6":16,"7":16,"8":16,"9":16,"10":16},"SpeedBoostPercent":{"0":20,"1":23,"2":25,"3":28,"4":30,"5":33,"6":33,"7":33,"8":33,"9":33,"10":33}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '24',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Mindbender'
  ),
  (
    'Pain Inverter',
    'https://wiki.guildwars.com/images/9/91/Pain_Inverter.jpg',
    false,
    'Hex Spell. ({{Duration}} seconds.) Deals {{PercentOfDamage}}% of the damage (maximum 80) back to target foe every time it does damage.',
    (SELECT id FROM skill_types WHERE name = 'Hex Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"Duration":{"0":6,"1":7,"2":8,"3":8,"4":9,"5":10,"6":10,"7":10,"8":10,"9":10,"10":10},"PercentOfDamage":{"0":100,"1":108,"2":116,"3":124,"4":132,"5":140,"6":140,"7":140,"8":140,"9":140,"10":140},"DamageTakenToReachCap":{"0":80,"1":75,"2":71,"3":66,"4":62,"5":57,"6":57,"7":57,"8":57,"9":57,"10":57}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '20',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Pain_Inverter'
  ),
  (
    'Radiation Field',
    'https://wiki.guildwars.com/images/3/31/Radiation_Field.jpg',
    false,
    'Ward Spell. (5 seconds.) Causes -{{HealthDegeneration}} Health degeneration to foes in the area. End effect: inflicts Disease condition ({{DiseaseDuration}} seconds) to foes in the area.',
    (SELECT id FROM skill_types WHERE name = 'Ward Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"HealthDegeneration":{"0":4,"1":4,"2":5,"3":5,"4":6,"5":6,"6":6,"7":6,"8":6,"9":6,"10":6},"DiseaseDuration":{"0":12,"1":14,"2":15,"3":17,"4":18,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20}}'::jsonb,
    15,
    NULL,
    NULL,
    NULL,
    NULL,
    2,
    '12',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Radiation_Field'
  ),
  (
    'Smooth Criminal',
    'https://wiki.guildwars.com/images/3/33/Smooth_Criminal.jpg',
    false,
    'Spell. ({{Duration}} seconds.) Disables one Spell. This skill becomes that Spell. You gain {{EnergyGain}} Energy.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"Duration":{"0":10,"1":12,"2":14,"3":16,"4":18,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"EnergyGain":{"0":5,"1":6,"2":7,"3":8,"4":9,"5":10,"6":10,"7":10,"8":10,"9":10,"10":10}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '20',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Smooth_Criminal'
  ),
  (
    'Summon Ice Imp',
    'https://wiki.guildwars.com/images/2/2a/Summon_Ice_Imp.jpg',
    false,
    'Spell. Summon a level {{IceImpLevel}} Ice Imp ({{Duration}} lifespan) that has Ice Spikes. Only 1 Asura Summon can be active a time.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"IceImpLevel":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"Duration":{"0":40,"1":44,"2":48,"3":52,"4":56,"5":60,"6":60,"7":60,"8":60,"9":60,"10":60}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    3,
    '60',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Summon_Ice_Imp'
  ),
  (
    'Summon Mursaat',
    'https://wiki.guildwars.com/images/6/61/Summon_Mursaat.jpg',
    false,
    'Spell. Summon a level {{MursaatLevel}} Mursaat ({{Duration}} lifespan) that has Enervating Charge. Only 1 Asura Summon can be active a time.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"MursaatLevel":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"Duration":{"0":40,"1":44,"2":48,"3":52,"4":56,"5":60,"6":60,"7":60,"8":60,"9":60,"10":60}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    3,
    '60',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Summon_Mursaat'
  ),
  (
    'Summon Naga Shaman',
    'https://wiki.guildwars.com/images/f/f0/Summon_Naga_Shaman.jpg',
    false,
    'Spell. Summon a level {{NagaShamanLevel}} Naga Shaman ({{Duration}} lifespan) that has Stoning. Only 1 Asura Summon can be active a time.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"NagaShamanLevel":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"Duration":{"0":40,"1":44,"2":48,"3":52,"4":56,"5":60,"6":60,"7":60,"8":60,"9":60,"10":60}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    3,
    '60',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Summon_Naga_Shaman'
  ),
  (
    'Summon Ruby Djinn',
    'https://wiki.guildwars.com/images/a/a0/Summon_Ruby_Djinn.jpg',
    false,
    'Spell. Summon a level {{RubyDjinnLevel}} Ruby Djinn ({{Duration}} lifespan) that has Immolate. Only 1 Asura Summon can be active a time.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"RubyDjinnLevel":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"Duration":{"0":40,"1":44,"2":48,"3":52,"4":56,"5":60,"6":60,"7":60,"8":60,"9":60,"10":60}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    3,
    '60',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Summon_Ruby_Djinn'
  ),
  (
    'Technobabble',
    'https://wiki.guildwars.com/images/0/0a/Technobabble.jpg',
    false,
    'Spell. Deals {{Damage}} damage to target and adjacent foes. Inflicts Dazed condition ({{DazedDuration}} seconds) on these foes if target was not a boss.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Asura rank' LIMIT 1),
    '{"Damage":{"0":30,"1":32,"2":34,"3":36,"4":38,"5":40,"6":40,"7":40,"8":40,"9":40,"10":40},"DazedDuration":{"0":3,"1":3,"2":4,"3":4,"4":5,"5":5,"6":5,"7":5,"8":5,"9":5,"10":5}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '10',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Technobabble'
  ),
  (
    '"By Ural''s Hammer!"',
    'https://wiki.guildwars.com/images/d/df/%22By_Ural%27s_Hammer%21%22.jpg',
    false,
    'Shout. (30 seconds.) Resurrect all dead party members in earshot with full Health and Energy. Affected party members deal {{IncreasedDamagePercent}}% more damage. Affected party members die when it ends, but do not receive a death penalty.',
    (SELECT id FROM skill_types WHERE name = 'Shout'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"IncreasedDamagePercent":{"0":25,"1":27,"2":28,"3":30,"4":31,"5":33,"6":33,"7":33,"8":33,"9":33,"10":33}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '60',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/%22By_Ural%27s_Hammer!%22'
  ),
  (
    '"Don''t Trip!"',
    'https://wiki.guildwars.com/images/c/c1/%22Don%27t_Trip%21%22.jpg',
    false,
    'Shout. ({{Duration}} seconds.) Prevents knock-down; affects party members within earshot.',
    (SELECT id FROM skill_types WHERE name = 'Shout'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"Duration":{"0":3,"1":3,"2":4,"3":4,"4":5,"5":5,"6":5,"7":5,"8":5,"9":5,"10":5}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '20',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/%22Don%27t_Trip!%22'
  ),
  (
    'Alkar''s Alchemical Acid',
    'https://wiki.guildwars.com/images/4/43/Alkar%27s_Alchemical_Acid.jpg',
    false,
    'Spell. Projectile: deals {{Damage}} damage to target and adjacent foes. Deals {{AdditionalDamage}} more damage and inflicts Cracked Armor condition ({{CrackedArmorDuration}} seconds) to Destroyers.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"Damage":{"0":40,"1":42,"2":44,"3":46,"4":48,"5":50,"6":50,"7":50,"8":50,"9":50,"10":50},"AdditionalDamage":{"0":45,"1":50,"2":55,"3":60,"4":65,"5":70,"6":70,"7":70,"8":70,"9":70,"10":70},"CrackedArmorDuration":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '10',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Alkar%27s_Alchemical_Acid'
  ),
  (
    'Black Powder Mine',
    'https://wiki.guildwars.com/images/5/50/Black_Powder_Mine.jpg',
    false,
    'Trap. (90 seconds.) Affects nearby foes. Deals {{FireDamage}} damage. Inflicts Blindness and Bleeding conditions ({{BlindAndBleedingDuration}} seconds). Easily interrupted.',
    (SELECT id FROM skill_types WHERE name = 'Trap'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"FireDamage":{"0":20,"1":22,"2":24,"3":26,"4":28,"5":30,"6":30,"7":30,"8":30,"9":30,"10":30},"BlindAndBleedingDuration":{"0":7,"1":8,"2":8,"3":9,"4":9,"5":10,"6":10,"7":10,"8":10,"9":10,"10":10}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    2,
    '20',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Black_Powder_Mine'
  ),
  (
    'Brawling Headbutt',
    'https://wiki.guildwars.com/images/b/be/Brawling_Headbutt.jpg',
    false,
    'Touch Skill. Deals {{Damage}} damage; causes knock-down.',
    (SELECT id FROM skill_types WHERE name = 'Touch Skill'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"Damage":{"0":45,"1":50,"2":55,"3":60,"4":65,"5":70,"6":70,"7":70,"8":70,"9":70,"10":70}}'::jsonb,
    NULL,
    7,
    NULL,
    NULL,
    NULL,
    0.75,
    '0',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Brawling_Headbutt'
  ),
  (
    'Breath of the Great Dwarf',
    'https://wiki.guildwars.com/images/0/0e/Breath_of_the_Great_Dwarf.jpg',
    false,
    'Spell. Removes burning and heals for {{Healing}} Health. Affects party members.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"Healing":{"0":50,"1":52,"2":54,"3":56,"4":58,"5":60,"6":60,"7":60,"8":60,"9":60,"10":60}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    0.25,
    '15',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Breath_of_the_Great_Dwarf'
  ),
  (
    'Drunken Master',
    'https://wiki.guildwars.com/images/b/b3/Drunken_Master.jpg',
    false,
    'Stance. ({{Duration}} seconds.) You move and attack {{SpeedIncreasePercentIfSober}}% faster if you are not drunk. You move and attack {{SpeedIncreasePercentIfDrunk}}% faster if you are drunk.',
    (SELECT id FROM skill_types WHERE name = 'Stance'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"Duration":{"0":72,"1":76,"2":79,"3":83,"4":86,"5":90,"6":90,"7":90,"8":90,"9":90,"10":90},"SpeedIncreasePercentIfSober":{"0":10,"1":11,"2":12,"3":13,"4":14,"5":15,"6":15,"7":15,"8":15,"9":15,"10":15},"SpeedIncreasePercentIfDrunk":{"0":25,"1":27,"2":28,"3":30,"4":31,"5":33,"6":33,"7":33,"8":33,"9":33,"10":33}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '60',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Drunken_Master'
  ),
  (
    'Dwarven Stability',
    'https://wiki.guildwars.com/images/4/4c/Dwarven_Stability.jpg',
    false,
    'Enchantment Spell. ({{Duration}} seconds.) Your stances last {{StanceDurationIncreasePercent}}% longer. You cannot be knocked-down if you activated this skill while drunk.',
    (SELECT id FROM skill_types WHERE name = 'Enchantment Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"Duration":{"0":24,"1":25,"2":26,"3":28,"4":29,"5":30,"6":30,"7":30,"8":30,"9":30,"10":30},"StanceDurationIncreasePercent":{"0":55,"1":64,"2":73,"3":82,"4":91,"5":100,"6":100,"7":100,"8":100,"9":100,"10":100}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0.25,
    '30',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Dwarven_Stability'
  ),
  (
    'Ear Bite',
    'https://wiki.guildwars.com/images/c/c6/Ear_Bite.jpg',
    false,
    'Touch Skill. Deals {{PiercingDamage}} piercing damage and inflicts Bleeding condition ({{BleedingDuration}} seconds).',
    (SELECT id FROM skill_types WHERE name = 'Touch Skill'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"PiercingDamage":{"0":50,"1":54,"2":58,"3":62,"4":66,"5":70,"6":70,"7":70,"8":70,"9":70,"10":70},"BleedingDuration":{"0":15,"1":17,"2":19,"3":21,"4":23,"5":25,"6":25,"7":25,"8":25,"9":25,"10":25}}'::jsonb,
    NULL,
    4,
    NULL,
    NULL,
    NULL,
    0.75,
    '0',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Ear_Bite'
  ),
  (
    'Great Dwarf Armor',
    'https://wiki.guildwars.com/images/e/e5/Great_Dwarf_Armor.jpg',
    false,
    'Enchantment Spell. ({{Duration}} seconds.) +24 armor and +60 maximum Health. Additional +24 armor against Destroyers.',
    (SELECT id FROM skill_types WHERE name = 'Enchantment Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"Duration":{"0":22,"1":26,"2":29,"3":33,"4":36,"5":40,"6":40,"7":40,"8":40,"9":40,"10":40}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '10',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Great_Dwarf_Armor'
  ),
  (
    'Great Dwarf Weapon',
    'https://wiki.guildwars.com/images/a/ab/Great_Dwarf_Weapon.jpg',
    false,
    'Weapon Spell. (20 seconds.) +{{Damage}} weapon damage and {{KnockDownChancePercent}}% chance to cause knock-down with attacks. Cannot self-target.',
    (SELECT id FROM skill_types WHERE name = 'Weapon Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"Damage":{"0":15,"1":16,"2":17,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"KnockDownChancePercent":{"0":28,"1":30,"2":33,"3":35,"4":38,"5":40,"6":40,"7":40,"8":40,"9":40,"10":40}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '5',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Great_Dwarf_Weapon'
  ),
  (
    'Light of Deldrimor',
    'https://wiki.guildwars.com/images/1/11/Light_of_Deldrimor.jpg',
    false,
    'Spell. Deals {{HolyDamage}} holy damage to foes in the area. Pings hidden objects within the area on the compass.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"HolyDamage":{"0":55,"1":60,"2":65,"3":70,"4":75,"5":80,"6":80,"7":80,"8":80,"9":80,"10":80}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0.75,
    '20',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Light_of_Deldrimor'
  ),
  (
    'Low Blow',
    'https://wiki.guildwars.com/images/8/86/Low_Blow.jpg',
    false,
    'Touch Skill. Deals {{Damage}} damage. Inflicts {{ConditionalDamage}} damage and Cracked Armor ({{CrackedArmorDuration}} seconds) if target foe is knocked down.',
    (SELECT id FROM skill_types WHERE name = 'Touch Skill'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"Damage":{"0":45,"1":50,"2":55,"3":60,"4":65,"5":70,"6":70,"7":70,"8":70,"9":70,"10":70},"ConditionalDamage":{"0":30,"1":34,"2":38,"3":42,"4":46,"5":50,"6":50,"7":50,"8":50,"9":50,"10":50},"CrackedArmorDuration":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20}}'::jsonb,
    NULL,
    6,
    NULL,
    NULL,
    NULL,
    0.75,
    '0',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Low_Blow'
  ),
  (
    'Snow Storm',
    'https://wiki.guildwars.com/images/a/a0/Snow_Storm.jpg',
    false,
    'Spell. Deals {{ColdDamage}} cold damage each second (5 seconds). Hits foes adjacent to target foe''s initial location.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Deldrimor rank' LIMIT 1),
    '{"ColdDamage":{"0":30,"1":32,"2":34,"3":36,"4":38,"5":40,"6":40,"7":40,"8":40,"9":40,"10":40}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '10',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Snow_Storm'
  ),
  (
    'Deft Strike',
    'https://wiki.guildwars.com/images/6/62/Deft_Strike.jpg',
    false,
    'Ranged Attack. Deals {{ArmorignoringDamage}} damage. Inflicts Bleeding condition ({{BleedingDuration}} seconds) if target foe has Cracked Armor.',
    (SELECT id FROM skill_types WHERE name = 'Ranged Attack'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"ArmorignoringDamage":{"0":18,"1":20,"2":23,"3":25,"4":28,"5":30,"6":30,"7":30,"8":30,"9":30,"10":30},"BleedingDuration":{"0":18,"1":20,"2":23,"3":25,"4":28,"5":30,"6":30,"7":30,"8":30,"9":30,"10":30}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0.5,
    '8',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Deft_Strike'
  ),
  (
    'Ebon Battle Standard of Courage',
    'https://wiki.guildwars.com/images/5/53/Ebon_Battle_Standard_of_Courage.jpg',
    false,
    'Ward Spell. ({{Duration}} seconds.) Allies in this ward have +24 armor and +24 more armor against Charr. Spirits are unaffected.',
    (SELECT id FROM skill_types WHERE name = 'Ward Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"Duration":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '20',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Ebon_Battle_Standard_of_Courage'
  ),
  (
    'Ebon Battle Standard of Honor',
    'https://wiki.guildwars.com/images/5/51/Ebon_Battle_Standard_of_Honor.jpg',
    false,
    'Ward Spell. ({{Duration}} seconds.) Allies in this ward deal +{{Damage}} damage and +{{DamageVsCharr}} more damage against Charr. Spirits are unaffected.',
    (SELECT id FROM skill_types WHERE name = 'Ward Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"Duration":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"Damage":{"0":8,"1":9,"2":11,"3":12,"4":14,"5":15,"6":15,"7":15,"8":15,"9":15,"10":15},"DamageVsCharr":{"0":7,"1":8,"2":8,"3":9,"4":9,"5":10,"6":10,"7":10,"8":10,"9":10,"10":10}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '20',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Ebon_Battle_Standard_of_Honor'
  ),
  (
    'Ebon Battle Standard of Wisdom',
    'https://wiki.guildwars.com/images/e/eb/Ebon_Battle_Standard_of_Wisdom.jpg',
    false,
    'Ward Spell. ({{Duration}} seconds.) Spells that allies in this ward cast have a {{HsrChancePercent}}% chance to recharge 50% faster. Spirits are unaffected.',
    (SELECT id FROM skill_types WHERE name = 'Ward Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"Duration":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"HsrChancePercent":{"0":44,"1":47,"2":50,"3":54,"4":57,"5":60,"6":60,"7":60,"8":60,"9":60,"10":60}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '20',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Ebon_Battle_Standard_of_Wisdom'
  ),
  (
    'Ebon Escape',
    'https://wiki.guildwars.com/images/b/bb/Ebon_Escape.jpg',
    false,
    'Spell. Heals you and target ally for {{Healing}}. Initial effect: Shadow Step to this ally. Cannot self-target.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"Healing":{"0":70,"1":78,"2":86,"3":94,"4":102,"5":110,"6":110,"7":110,"8":110,"9":110,"10":110}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0.25,
    '10',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Ebon_Escape'
  ),
  (
    'Ebon Vanguard Assassin Support',
    'https://wiki.guildwars.com/images/0/03/Ebon_Vanguard_Assassin_Support.jpg',
    false,
    'Spell. Summon a level {{AssassinLevel}} assassin that has Iron Palm, Fox Fangs, and Nine Tail Strike; it Shadow Steps to this foe. If this foe is a Charr, the assassin lives for {{DurationVsCharr}} seconds. If target foe is not a Charr, the Assassin lives for {{DurationVsOtherFoes}} seconds.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"AssassinLevel":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"DurationVsCharr":{"0":24,"1":25,"2":26,"3":28,"4":29,"5":30,"6":30,"7":30,"8":30,"9":30,"10":30},"DurationVsOtherFoes":{"0":12,"1":13,"2":13,"3":14,"4":14,"5":15,"6":15,"7":15,"8":15,"9":15,"10":15}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '30',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Ebon_Vanguard_Assassin_Support'
  ),
  (
    'Ebon Vanguard Sniper Support',
    'https://wiki.guildwars.com/images/1/16/Ebon_Vanguard_Sniper_Support.jpg',
    false,
    'Spell. Deals {{PiercingDamage}} piercing damage and inflicts Bleeding condition ({{BleedingDuration}} seconds). 10% chance of +{{AdditionalPiercingDamage}} piercing damage. 25% chance of +{{AdditionalPiercingDamage}} piercing damage if target foe is a Charr.',
    (SELECT id FROM skill_types WHERE name = 'Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"PiercingDamage":{"0":54,"1":61,"2":68,"3":76,"4":83,"5":90,"6":90,"7":90,"8":90,"9":90,"10":90},"AdditionalPiercingDamage":{"0":540,"1":612,"2":684,"3":756,"4":828,"5":900,"6":900,"7":900,"8":900,"9":900,"10":900},"BleedingDuration":{"0":5,"1":9,"2":13,"3":17,"4":21,"5":25,"6":25,"7":25,"8":25,"9":25,"10":25}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '15',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Ebon_Vanguard_Sniper_Support'
  ),
  (
    'Signet of Infection',
    'https://wiki.guildwars.com/images/6/66/Signet_of_Infection.jpg',
    false,
    'Signet. Inflicts Diseased condition {{DiseaseDuration}} seconds if target foe is Bleeding.',
    (SELECT id FROM skill_types WHERE name = 'Signet'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"DiseaseDuration":{"0":13,"1":14,"2":16,"3":17,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20}}'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '10',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Signet_of_Infection'
  ),
  (
    'Sneak Attack',
    'https://wiki.guildwars.com/images/8/87/Sneak_Attack.jpg',
    false,
    'Melee Attack. Inflicts Blindness ({{BlindDuration}} seconds). Counts as a lead attack.',
    (SELECT id FROM skill_types WHERE name = 'Melee Attack'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"BlindDuration":{"0":5,"1":6,"2":6,"3":7,"4":7,"5":8,"6":8,"7":8,"8":8,"9":8,"10":8}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '5',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Sneak_Attack'
  ),
  (
    'Tryptophan Signet',
    'https://wiki.guildwars.com/images/7/70/Tryptophan_Signet.jpg',
    false,
    'Signet. ({{Duration}} seconds.) Target and adjacent foes move and attack {{SpeedReductionPercent}}% slower.',
    (SELECT id FROM skill_types WHERE name = 'Signet'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"Duration":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"SpeedReductionPercent":{"0":23,"1":26,"2":30,"3":33,"4":37,"5":40,"6":40,"7":40,"8":40,"9":40,"10":40}}'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    '15',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Tryptophan_Signet'
  ),
  (
    'Weakness Trap',
    'https://wiki.guildwars.com/images/0/0d/Weakness_Trap.jpg',
    false,
    'Trap. (90 seconds.) Affects nearby foes. Deals {{LightningDamage}} lightning damage. Inflicts Weakness condition ({{WeaknessDuration}} seconds). Knocks-down Charr. Easily interrupted.',
    (SELECT id FROM skill_types WHERE name = 'Trap'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"WeaknessDuration":{"0":10,"1":12,"2":14,"3":16,"4":18,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"LightningDamage":{"0":24,"1":29,"2":34,"3":40,"4":45,"5":50,"6":50,"7":50,"8":50,"9":50,"10":50}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    2,
    '30',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Weakness_Trap'
  ),
  (
    'Winds',
    'https://wiki.guildwars.com/images/0/0e/Winds.jpg',
    false,
    'Ebon Vanguard Ritual. Creates a level {{Level}} spirit ({{Duration}} second lifespan.) Affects foes within range. 15% chance to miss with ranged attacks.',
    (SELECT id FROM skill_types WHERE name = 'Ebon Vanguard Ritual'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Ebon Vanguard rank' LIMIT 1),
    '{"Level":{"0":4,"1":5,"2":6,"3":8,"4":9,"5":10,"6":10,"7":10,"8":10,"9":10,"10":10},"Duration":{"0":54,"1":61,"2":68,"3":76,"4":83,"5":90,"6":90,"7":90,"8":90,"9":90,"10":90}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    5,
    '30',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Winds'
  ),
  (
    '"Dodge This!"',
    'https://wiki.guildwars.com/images/4/4b/%22Dodge_This%21%22.jpg',
    false,
    'Shout. ({{Duration}} seconds.) Your next attack is unblockable and deals +{{Damage}} damage.',
    (SELECT id FROM skill_types WHERE name = 'Shout'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"Duration":{"0":16,"1":17,"2":18,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20},"Damage":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20}}'::jsonb,
    NULL,
    4,
    NULL,
    NULL,
    NULL,
    0,
    '0',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/%22Dodge_This!%22'
  ),
  (
    '"Finish Him!"',
    'https://wiki.guildwars.com/images/6/61/%22Finish_Him%21%22.jpg',
    false,
    'Shout. Deals {{Damage}} damage and inflicts Cracked Armor and Deep Wound conditions ({{CrackedArmorAndDeepWoundDuration}} seconds). No effect unless target foe has less than 50% Health.',
    (SELECT id FROM skill_types WHERE name = 'Shout'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"Damage":{"0":44,"1":51,"2":58,"3":66,"4":73,"5":80,"6":80,"7":80,"8":80,"9":80,"10":80},"CrackedArmorAndDeepWoundDuration":{"0":12,"1":14,"2":15,"3":17,"4":18,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '15',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/%22Finish_Him!%22'
  ),
  (
    '"I Am Unstoppable!"',
    'https://wiki.guildwars.com/images/e/ed/%22I_Am_Unstoppable%21%22.jpg',
    false,
    'Shout. ({{Duration}} seconds.) You have +24 armor and cannot be knocked-down or Crippled.',
    (SELECT id FROM skill_types WHERE name = 'Shout'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"Duration":{"0":16,"1":17,"2":18,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '30',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/%22I_Am_Unstoppable!%22'
  ),
  (
    '"I Am the Strongest!"',
    'https://wiki.guildwars.com/images/e/ec/%22I_Am_the_Strongest%21%22.jpg',
    false,
    'Shout. Your next {{OfAttacks}} attacks deal +{{AdditionalDamage}} damage.',
    (SELECT id FROM skill_types WHERE name = 'Shout'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"OfAttacks":{"0":5,"1":6,"2":6,"3":7,"4":7,"5":8,"6":8,"7":8,"8":8,"9":8,"10":8},"AdditionalDamage":{"0":14,"1":15,"2":16,"3":18,"4":19,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '20',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/%22I_Am_the_Strongest!%22'
  ),
  (
    '"You Are All Weaklings!"',
    'https://wiki.guildwars.com/images/a/a4/%22You_Are_All_Weaklings%21%22.jpg',
    false,
    'Shout. Inflicts Weakness condition ({{WeaknessDuration}} seconds). Also affects adjacent foes.',
    (SELECT id FROM skill_types WHERE name = 'Shout'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"WeaknessDuration":{"0":8,"1":9,"2":10,"3":10,"4":11,"5":12,"6":12,"7":12,"8":12,"9":12,"10":12}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '12',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/%22You_Are_All_Weaklings!%22'
  ),
  (
    '"You Move Like a Dwarf!"',
    'https://wiki.guildwars.com/images/6/6a/%22You_Move_Like_a_Dwarf%21%22.jpg',
    false,
    'Shout. Deals {{Damage}} damage, causes knock-down, and inflicts Crippled condition ({{CrippledDuration}} seconds).',
    (SELECT id FROM skill_types WHERE name = 'Shout'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"Damage":{"0":44,"1":51,"2":58,"3":66,"4":73,"5":80,"6":80,"7":80,"8":80,"9":80,"10":80},"CrippledDuration":{"0":8,"1":9,"2":11,"3":12,"4":14,"5":15,"6":15,"7":15,"8":15,"9":15,"10":15}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '10',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/%22You_Move_Like_a_Dwarf!%22'
  ),
  (
    'A Touch of Guile',
    'https://wiki.guildwars.com/images/2/2d/A_Touch_of_Guile.jpg',
    false,
    'Touch Hex Spell. Deals {{ArmorignoringDamage}} damage. Target foe cannot attack ({{Duration}} seconds) if it was knocked-down.',
    (SELECT id FROM skill_types WHERE name = 'Touch Hex Spell'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"ArmorignoringDamage":{"0":44,"1":51,"2":58,"3":66,"4":73,"5":80,"6":80,"7":80,"8":80,"9":80,"10":80},"Duration":{"0":5,"1":6,"2":6,"3":7,"4":7,"5":8,"6":8,"7":8,"8":8,"9":8,"10":8}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0.75,
    '15',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/A_Touch_of_Guile'
  ),
  (
    'Club of a Thousand Bears',
    'https://wiki.guildwars.com/images/d/dc/Club_of_a_Thousand_Bears.jpg',
    false,
    'Melee Attack. Deals +{{DamagePerFoe}} damage for each adjacent foe (maximum 60 damage). Causes knock-down if target foe is non-human.',
    (SELECT id FROM skill_types WHERE name = 'Melee Attack'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"DamagePerFoe":{"0":6,"1":7,"2":7,"3":8,"4":8,"5":9,"6":9,"7":9,"8":9,"9":9,"10":9}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '12',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Club_of_a_Thousand_Bears'
  ),
  (
    'Feel No Pain',
    'https://wiki.guildwars.com/images/f/fe/Feel_No_Pain.jpg',
    false,
    'Skill. (30 seconds.) You have +{{HealthRegeneration}} Health regeneration. You have +{{ConditionalMaximumHealth}} maximum Health if you are drunk when activating this skill.',
    (SELECT id FROM skill_types WHERE name = 'Skill'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"HealthRegeneration":{"0":2,"1":2,"2":2,"3":3,"4":3,"5":3,"6":3,"7":3,"8":3,"9":3,"10":3},"ConditionalMaximumHealth":{"0":200,"1":220,"2":240,"3":260,"4":280,"5":300,"6":300,"7":300,"8":300,"9":300,"10":300}}'::jsonb,
    5,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '20',
    false,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Feel_No_Pain'
  ),
  (
    'Raven Blessing',
    'https://wiki.guildwars.com/images/0/0a/Raven_Blessing.jpg',
    false,
    'Elite Form. You lose all effects and take on the aspect of the Raven (60 seconds). All your attributes are set to 0 and raven attacks replace your skills, and you have 80 armor, {{MaximumHealth}} Health, and a {{BlockChancePercent}}% block chance.',
    (SELECT id FROM skill_types WHERE name = 'Elite Form'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"MaximumHealth":{"0":660,"1":668,"2":676,"3":684,"4":692,"5":700,"6":700,"7":700,"8":700,"9":700,"10":700},"BlockChancePercent":{"0":20,"1":22,"2":24,"3":26,"4":28,"5":30,"6":30,"7":30,"8":30,"9":30,"10":30}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '60',
    true,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Raven_Blessing'
  ),
  (
    'Ursan Blessing',
    'https://wiki.guildwars.com/images/7/7b/Ursan_Blessing.jpg',
    false,
    'Elite Form. You lose all effects and take on the aspect of the bear (60 seconds). All your attributes are set to 0 and bear attacks replace your skills, and you have 100 armor and {{MaximumHealth}} Health.',
    (SELECT id FROM skill_types WHERE name = 'Elite Form'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"MaximumHealth":{"0":750,"1":760,"2":770,"3":780,"4":790,"5":800,"6":800,"7":800,"8":800,"9":800,"10":800}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '60',
    true,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Ursan_Blessing'
  ),
  (
    'Volfen Blessing',
    'https://wiki.guildwars.com/images/b/b2/Volfen_Blessing.jpg',
    false,
    'Elite Form. You lose all effects and take on the aspect of the wolf (60 seconds). All your attributes are set to 0 and wolf attacks replace your skills, and you have 80 armor, {{MaximumHealth}} Health and {{HealthRegeneration}} Health regeneration.',
    (SELECT id FROM skill_types WHERE name = 'Elite Form'),
    NULL,
    (SELECT id FROM attributes WHERE name = 'Norn rank' LIMIT 1),
    '{"MaximumHealth":{"0":660,"1":668,"2":676,"3":684,"4":692,"5":700,"6":700,"7":700,"8":700,"9":700,"10":700},"HealthRegeneration":{"0":2,"1":2,"2":3,"3":3,"4":4,"5":4,"6":4,"7":4,"8":4,"9":4,"10":4}}'::jsonb,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    '60',
    true,
    (SELECT id FROM releases WHERE name = 'Eye of the North'),
    'PvE-only',
    'https://wiki.guildwars.com/wiki/Volfen_Blessing'
  )
ON CONFLICT (name) DO UPDATE SET
  icon = EXCLUDED.icon,
  is_high_res_icon = EXCLUDED.is_high_res_icon,
  description = EXCLUDED.description,
  skill_type_id = EXCLUDED.skill_type_id,
  profession_id = EXCLUDED.profession_id,
  attribute_id = EXCLUDED.attribute_id,
  attribute_progression = EXCLUDED.attribute_progression,
  energy_cost = EXCLUDED.energy_cost,
  adrenaline_cost = EXCLUDED.adrenaline_cost,
  upkeep_cost = EXCLUDED.upkeep_cost,
  sacrifice_cost = EXCLUDED.sacrifice_cost,
  overcast_cost = EXCLUDED.overcast_cost,
  activation_time = EXCLUDED.activation_time,
  recharge_time = EXCLUDED.recharge_time,
  is_elite = EXCLUDED.is_elite,
  release_id = EXCLUDED.release_id,
  limitation = EXCLUDED.limitation,
  wiki_url = EXCLUDED.wiki_url;
